plugins {
    id "com.android.application"
}

android {
    namespace "com.tempest07.bondcentre"
    compileSdk 35

    defaultConfig {
        applicationId "com.tempest07.bondcentre"
        minSdk 26
        targetSdk 35
        versionCode 4
        versionName "0.3.1"
    }

    buildFeatures {
        buildConfig true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation "androidx.work:work-runtime:2.11.2"
}
